#!/usr/bin/env bash
# Builds the WebGL native archive and generates the exception-helper shim.
#
# Rust's std for wasm32-unknown-emscripten is built with panic=unwind, so the archive references
# Emscripten's C++ exception machinery (__cxa_*, invoke_*). Unity's WebGL main module disables
# exceptions and longjmp, so those symbols are absent and the link fails. The shim defines the
# __cxa* helpers as aborts (the invoke_* trampolines cannot be shimmed: Emscripten asserts on them).
# aborts: they are only reachable if a Rust panic unwinds, which the C ABI already catches at its
# boundary (crates/anny-capi/src/lib.rs), and Unity's build cannot unwind at all.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
PACKAGE="$ROOT/integrations/unity/package"
ARCHIVE="$ROOT/target/wasm32-unknown-emscripten/release/libanny_capi.a"
SHIM="$PACKAGE/Plugins/WebGL/anny-eh-shim.jslib"
SYMBOLS=/tmp/anny-eh-symbols.txt

# shellcheck disable=SC1090
source "$HOME/emsdk/emsdk_env.sh" >/dev/null 2>&1

echo "=== building the wasm archive (staticlib: no link, so wasm-opt is not involved)"
cargo rustc -p anny-capi --manifest-path "$ROOT/Cargo.toml" \
    --target wasm32-unknown-emscripten --release --crate-type staticlib

mkdir -p "$PACKAGE/Plugins/WebGL"
cp "$ARCHIVE" "$PACKAGE/Plugins/WebGL/libanny.a"

echo "=== generating the shim from the archive's undefined symbols"
"$EMSDK/upstream/bin/llvm-nm" -u "$ARCHIVE" 2>/dev/null \
    | awk '{print $NF}' \
    | grep -E '^(__cxa|__resumeException|llvm_eh_typeid_for)' \
    | sort -u > "$SYMBOLS"

{
    echo "// GENERATED by tools/build-native-webgl.sh - do not edit by hand."
    echo "// Satisfies the exception helpers Rust's unwind-built std references; see the script header."
    echo "mergeInto(LibraryManager.library, {"
    while read -r symbol; do
        echo "  $symbol: function () { abort('unreachable: $symbol'); },"
    done < "$SYMBOLS"
    echo "});"
} > "$SHIM"

echo "=== shim symbols: $(wc -l < "$SYMBOLS")"
grep -E '__cxa|invoke_' "$SHIM" | head -3
